# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ModuleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LSRFramework'
  pod 'JSONModel'
  pod 'SSZipArchive'
  pod 'AFNetworking'
  #pod 'XEngineSDK'
  #pod 'UIModule'
	
# Pods for XEngineUIModule
  pod 'XEngineUIModule', :path =>'../iOS'	
 
# Pods for XEngineSDK
  pod 'XEngineSDK', :path =>'../iOS'

 target 'ModuleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModuleAppUITests' do
    # Pods for testing
  end

end
